# Author: Jonathan Starck (jonathan.starck@aiddevs.com)
# gitflow.yml (c) 2024
# Desc: description
# Created:  2024-02-20T14:18:38.404Z
# Modified: 2024-02-20T14:28:42.358Z

on:
  pull_request:
    types:
      - opened
      - closed
      - labeled
name: "⚙️ Gitflow: Release Workflows"
jobs:
  release_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitflow-workflow-action release workflows
        id: release_workflow
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: "dev"
          main_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}